### ISSUE TITLE
Error: Bad Memory Access causes capa script/binary to fail and exit

### ISSUE THREAD

**Issue by j3dw4rds** [fireeye/capa#176]
<img width="921" alt="Screen Shot 2020-07-22 at 12 45 09 PM" src="https://user-images.githubusercontent.com/25807782/88210109-44dffc80-cc19-11ea-9cd2-5358ff83a063.png">

Unsure what's happening or why this file in particular.

**Comment by j3dw4rds** [comment]
`C:\Users\jemblem13\Desktop>capa-v1.0.0-win.exe -v C:\Users\jemblem13\Desktop\4790845268590592\987dbef97c27a6f1f45417d3d29eafdf9dcc8c7dee0ef659d0bf0e5424a00b8c
104 functions [00:00, 107.08 functions/s]
Traceback (most recent call last):
  File "capa\main.py", line 646, in <module>
  File "capa\main.py", line 556, in main
  File "capa\main.py", line 106, in find_capabilities
  File "capa\main.py", line 63, in find_function_capabilities
  File "capa\features\extractors\viv\__init__.py", line 78, in extract_insn_features
  File "capa\features\extractors\viv\insn.py", line 452, in extract_features
  File "capa\features\extractors\viv\insn.py", line 219, in extract_insn_string_features
  File "capa\features\extractors\viv\insn.py", line 185, in read_string
  File "site-packages\envi\memory.py", line 459, in readMemory
envi.exc.SegmentationViolation: SegmentationViolation('Bad Memory Access: 0x402398',)
[1708] Failed to execute script main`

**Comment by williballenthin** [comment]
definitely a bug in capa, thanks for reporting! I'll address this today.

**Comment by williballenthin** [comment]
ok, so we're dealing with a weird binary. before i figure a solution, let me document what is happening:

The PE has one section `.rdata`:
![image](https://user-images.githubusercontent.com/156560/88243311-46c3b300-cc4d-11ea-9508-e0be82283129.png)

This is where vivisect is trying to read a string. However, this section is mapped as `WX` but *not* `R`. Vivisect faithfully raises a segmentation violation here, because the data is not marked as readable.

I didn't realize you could have a non-readable section and still do something meaningful. TIL.
