### ISSUE TITLE
linter exception in --thorough mode

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#188]
```
python scripts/lint.py rules/nursery/hash-data-using-murmur2.yml --thorough -vv
INFO:capa.lint:successfully loaded 1 rules
INFO:capa.lint:collecting potentially referenced samples
DEBUG:capa.lint:hash data using murmur2
Traceback (most recent call last):
  File "scripts/lint.py", line 533, in <module>
    sys.exit(main())
  File "scripts/lint.py", line 524, in main
    did_violate = lint(ctx, rules)
  File "scripts/lint.py", line 425, in lint
    did_suggest_fix = lint_rule(ctx, rule) or did_suggest_fix
  File "scripts/lint.py", line 388, in lint_rule
    lint_features(ctx, rule),
  File "scripts/lint.py", line 277, in run_lints
    if lint.check_rule(ctx, rule):
  File "scripts/lint.py", line 183, in check_rule
    for example in rule.meta.get("examples", []):
TypeError: 'NoneType' object is not iterable
```

**Comment by williballenthin** [comment]
```DEBUG:capa.lint:hash data using murmur2```

**Comment by williballenthin** [comment]
this is because there is a key `examples` but no entries:
![image](https://user-images.githubusercontent.com/156560/88321982-4246db00-ccdd-11ea-8c30-bb89b38eca1b.png)
