### ISSUE TITLE
Right click tree-view index exception

### ISSUE THREAD

**Issue by stevemk14ebr** [fireeye/capa#315]
Right clicking in the capa-explorer in the grey area throws an invalid index exception as no UI element is selected:

```
Traceback (most recent call last):
  File "c:\users\steve\source\repos\capa\capa\ida\plugin\view.py", line 257, in slot_custom_context_menu_requested
    item = self.map_index_to_source_item(model_index)
  File "c:\users\steve\source\repos\capa\capa\ida\plugin\view.py", line 104, in map_index_to_source_item
    raise ValueError("invalid index")
ValueError: invalid index
```

This pollutes the output window.

**Comment by mike-hunhoff** [comment]
Thank you for reporting @stevemk14ebr! This is addressed in #316.
