### ISSUE TITLE
explorer: initialize rules directory

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#462]
```py
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\capa\ida\plugin\form.py", line 1175, in slot_change_rules_dir
    path = self.ask_user_directory()
  File "C:\Python37\lib\site-packages\capa\ida\plugin\form.py", line 1146, in ask_user_directory
    self.parent, "Please select a capa rules directory", settings.user["rule_path"]
  File "C:\Python37\lib\site-packages\ida_settings\ida_settings.py", line 265, in __getitem__
    return self.get_value(key)
  File "C:\Python37\lib\site-packages\ida_settings\ida_settings.py", line 425, in get_value
    return self._qsettings.get_value(key)
  File "C:\Python37\lib\site-packages\ida_settings\ida_settings.py", line 355, in get_value
    raise KeyError("key not found")
KeyError: 'key not found'
```

seen by @Ana06 

> I have followed the instruction in the readme: installed capa and copy `capa_Explorer.py` to the plugins folder. I run the plugin, found the Settings button (founding the settings took me like 5 minutes... it doesn't look like a button!)  and I selected change default rules directory... and I got that error

**Comment by williballenthin** [comment]
> if it's the first time running the plugin it will prompt you for a rules directory when you click the analyze button

> but if you go to change the rules directory before that there is no key

from @mike-hunhoff

**Comment by mike-hunhoff** [comment]
thanks for the catch @Ana06. I have improved the handling of this case in #464.
