### ISSUE TITLE
key not found

### ISSUE THREAD

**Issue by whitepoet** [fireeye/capa#508]
```
Traceback (most recent call last):
  File "C:\Users\whitepoet\AppData\Roaming\Python\Python38\site-packages\capa\ida\plugin\form.py", line 1175, in slot_change_rules_dir
    path = self.ask_user_directory()
  File "C:\Users\whitepoet\AppData\Roaming\Python\Python38\site-packages\capa\ida\plugin\form.py", line 1146, in ask_user_directory
    self.parent, "Please select a capa rules directory", settings.user.get("rule_path", "")
  File "C:\Users\whitepoet\AppData\Roaming\Python\Python38\site-packages\ida_settings\ida_settings.py", line 265, in __getitem__
    return self.get_value(key)
  File "C:\Users\whitepoet\AppData\Roaming\Python\Python38\site-packages\ida_settings\ida_settings.py", line 425, in get_value
    return self._qsettings.get_value(key)
  File "C:\Users\whitepoet\AppData\Roaming\Python\Python38\site-packages\ida_settings\ida_settings.py", line 355, in get_value
    raise KeyError("key not found")
KeyError: 'key not found'
```

i used the change in the `form.py` as #462 said, but it did not work.

**Comment by williballenthin** [comment]
the stack trace source snippets indicate you've applied the fixes, but the exception doesn't make sense there. this makes me think one of two things:
  - have you restarted IDA between patching `form.py`? you have to do this because IDA caches the python modules. 
  - have you removed any python cache files (`.pyc` or `__pycache__` directories)?

**Comment by whitepoet** [comment]
ok,it is useful, thanks!
