### ISSUE TITLE
UnicodeDecodeError raised

### ISSUE THREAD

**Issue by Coffeeri** [fireeye/capa#559]
### Description
When analyzing a batch of malware samples, some of them raise a UnicodeDecodeError.

### Steps to Reproduce

I simply ran the following command (with and without `--json --quiet` options..)
```shell
> capa sample_path
```

**Expected behavior:**
Return a valid report

**Actual behavior:**
Program exits with a raised error:
```python
Traceback (most recent call last):
  File "main.py", line 812, in <module>
  File "main.py", line 707, in main
  File "main.py", line 346, in get_extractor
  File "main.py", line 329, in get_extractor_py3
  File "main.py", line 278, in get_workspace
  File "viv_utils/__init__.py", line 101, in getWorkspace
  File "vivisect/__init__.py", line 2676, in loadFromFile
  File "vivisect/parsers/pe.py", line 36, in parseFile
  File "vivisect/parsers/pe.py", line 366, in loadPeIntoWorkspace
  File "PE/__init__.py", line 452, in getImports
  File "PE/__init__.py", line 1172, in __getattr__
  File "PE/__init__.py", line 796, in parseImports
  File "PE/__init__.py", line 828, in parseImportTable
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
```
or

```python
TB like above ..
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1: invalid start byte
```

### Versions
OS: 20.04.1-Ubuntu
Capa-bin v1.6.3-0-gc547519

**Comment by r0ny123** [comment]
see #469 and https://github.com/fireeye/capa/issues/469#issuecomment-796421050

**Comment by Coffeeri** [comment]
> see #469 and [#469 (comment)](https://github.com/fireeye/capa/issues/469#issuecomment-796421050)

I can confirm, that there have accumulated multiple *.viv files. 
But shouldn't the raised error be `..is an invalid .viv file. It may have been generated with Python 2 (incompatible with Python 3)` since the following have been merged?
- williballenthin/viv-utils#16
- #479

**Comment by r0ny123** [comment]
Can you try removing the .viv files from directory?

**Comment by mr-tz** [comment]
If @r0ny123's solution doesn't help, can you please provide details on the files (type, name, etc.) that this occurs on?

**Comment by Coffeeri** [comment]
> Can you try removing the .viv files from directory?
Yes, but I did not solve the problem.

> If @r0ny123's solution doesn't help, can you please provide details on the files (type, name, etc.) that this occurs on?
I have noticed that I get the exception mostly when analyzing  PE32 files, dumped from memory. It seems that this might not be an issue of capa. 

Closing for now. If I have more data to share, I will reopen this issue. Thank you!
