### ISSUE TITLE
ida_settings not found (python 3.9.6, IDA Pro 7.5 sp3)

### ISSUE THREAD

**Issue by 0xdarkfloyd** [fireeye/capa#680]
Dear Capa team, do you have any suggestion about it? Thank you

C:\Users\User\Desktop\IDA\IDA7.5happy\plugins\capa_explorer.py: No module named 'ida_settings'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\IDA\IDA7.5happy\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/User/Desktop/IDA/IDA7.5happy/plugins/capa_explorer.py", line 9, in <module>
    from capa.ida.plugin import CapaExplorerPlugin
  File "C:\Users/User/Desktop/IDA/IDA7.5happy/plugins\capa\ida\plugin\__init__.py", line 14, in <module>
    from capa.ida.plugin.form import CapaExplorerForm
  File "C:\Users/User/Desktop/IDA/IDA7.5happy/plugins\capa\ida\plugin\form.py", line 18, in <module>
    import ida_settings
ModuleNotFoundError: No module named 'ida_settings'

**Comment by williballenthin** [comment]
yeah, you'll have to be sure that the python installation used by IDA has the capa deps installed. `ida-settings` is declared here: https://github.com/fireeye/capa/blob/master/setup.py#L20

so it *should* be installed when you do `pip install flare-capa`. if you've noticed this isn't working as expected, please let us know and we can try to reproduce and triage.
