### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'partition'

### ISSUE THREAD

**Issue by davidep** [fireeye/capa#684]
I noticed that a sample that was analyzed fine with capa 1.6 cause errors now with capa 2.0
This was tested on an Ubuntu 18.04 with REMnux, but the issue is the same with the release file downloaded from github.

Results with capa 2.0
```
$ ./capa notPetya.dll 
loading : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 579/579 [00:00<00:00, 2865.65 rules/s]
Traceback (most recent call last):
  File "main.py", line 1004, in <module>
  File "main.py", line 886, in main
  File "main.py", line 114, in find_file_capabilities
  File "features/extractors/pefile.py", line 148, in extract_file_features
  File "features/extractors/pefile.py", line 124, in extract_file_features
  File "features/extractors/pefile.py", line 36, in extract_file_export_names
AttributeError: 'NoneType' object has no attribute 'partition'
[8364] Failed to execute script main

$ md5sum notPetya.dll 
71b6a493388e7d0b40c83ce903bc6b04  notPetya.dll
```

**Expected behavior:**
Results with capa 1.6
```
$ ./capa notPetya.dll 
loading : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 485/485 [00:00<00:00, 2956.09     rules/s]
matching: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 175/175 [00:06<00:00, 27.45 functions/s]
+------------------------+------------------------------------------------------------------------------------+
| md5                    | 71b6a493388e7d0b40c83ce903bc6b04                                                   |
| sha1                   | 34f917aaba5684fbe56d3c57d48ef2a1aa7cf06d                                           |
| sha256                 | 027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745                   |
| path                   | notPetya.dll                                                                       |
+------------------------+------------------------------------------------------------------------------------+

+------------------------+------------------------------------------------------------------------------------+
| ATT&CK Tactic          | ATT&CK Technique                                                                   |
|------------------------+------------------------------------------------------------------------------------|
| DEFENSE EVASION        | Obfuscated Files or Information [T1027]                                            |
|                        | Virtualization/Sandbox Evasion::System Checks [T1497.001]                          |
| DISCOVERY              | File and Directory Discovery [T1083]                                               |
|                        | Process Discovery [T1057]                                                          |
|                        | Software Discovery [T1518]                                                         |
|                        | System Information Discovery [T1082]                                               |
|                        | System Network Configuration Discovery [T1016]                                     |
| EXECUTION              | Command and Scripting Interpreter [T1059]                                          |
|                        | Shared Modules [T1129]                                                             |
|                        | System Services::Service Execution [T1569.002]                                     |
| IMPACT                 | System Shutdown/Reboot [T1529]                                                     |
| PRIVILEGE ESCALATION   | Access Token Manipulation [T1134]                                                  |
+------------------------+------------------------------------------------------------------------------------+

+-----------------------------+-------------------------------------------------------------------------------+
| MBC Objective               | MBC Behavior                                                                  |
|-----------------------------+-------------------------------------------------------------------------------|
| ANTI-BEHAVIORAL ANALYSIS    | Debugger Detection::Software Breakpoints [B0001.025]                          |
|                             | Debugger Detection::Timing/Delay Check GetTickCount [B0001.032]               |
|                             | Virtual Machine Detection [B0009]                                             |
| COMMAND AND CONTROL         | C2 Communication::Receive Data [B0030.002]                                    |
|                             | C2 Communication::Send Data [B0030.001]                                       |
| COMMUNICATION               | DNS Communication::Resolve [C0011.001]                                        |
|                             | Interprocess Communication::Connect Pipe [C0003.002]                          |
|                             | Interprocess Communication::Create Pipe [C0003.001]                           |
|                             | Interprocess Communication::Read Pipe [C0003.003]                             |
|                             | Socket Communication::Get Socket Status [C0001.012]                           |
|                             | Socket Communication::Initialize Winsock Library [C0001.009]                  |
|                             | Socket Communication::Receive Data [C0001.006]                                |
|                             | Socket Communication::Send Data [C0001.007]                                   |
|                             | Socket Communication::Set Socket Config [C0001.001]                           |
| CRYPTOGRAPHY                | Decrypt Data [C0031]                                                          |
|                             | Encrypt Data::AES [C0027.001]                                                 |
|                             | Encrypt Data [C0027]                                                          |
|                             | Generate Pseudo-random Sequence::Use API [C0021.003]                          |
| DATA                        | Compression Library [C0060]                                                   |
|                             | Encoding::XOR [C0026.002]                                                     |
| DEFENSE EVASION             | Obfuscated Files or Information::Encoding-Standard Algorithm [E1027.m02]      |
|                             | Obfuscated Files or Information::Encryption-Standard Algorithm [E1027.m05]    |
| EXECUTION                   | Install Additional Program [B0023]                                            |
| FILE SYSTEM                 | Delete File [C0047]                                                           |
|                             | Read File [C0051]                                                             |
|                             | Write File [C0052]                                                            |
| PROCESS                     | Create Process [C0017]                                                        |
|                             | Create Thread [C0038]                                                         |
|                             | Resume Thread [C0054]                                                         |
|                             | Terminate Process [C0018]                                                     |
|                             | Terminate Thread [C0039]                                                      |
+-----------------------------+-------------------------------------------------------------------------------+

+------------------------------------------------------+------------------------------------------------------+
| CAPABILITY                                           | NAMESPACE                                            |
|------------------------------------------------------+------------------------------------------------------|
| check for software breakpoints                       | anti-analysis/anti-debugging/debugger-detection      |
| check for time delay via GetTickCount (2 matches)    | anti-analysis/anti-debugging/debugger-detection      |
| reference anti-VM strings targeting VirtualBox       | anti-analysis/anti-vm/vm-detection                   |
| receive data                                         | communication                                        |
| send data                                            | communication                                        |
| connect network resource                             | communication/http                                   |
| connect pipe                                         | communication/named-pipe/connect                     |
| create pipe                                          | communication/named-pipe/create                      |
| read pipe                                            | communication/named-pipe/read                        |
| get socket status (3 matches)                        | communication/socket                                 |
| initialize Winsock library                           | communication/socket                                 |
| set socket configuration (2 matches)                 | communication/socket                                 |
| decode data using Base64 via WinAPI (2 matches)      | data-manipulation/encoding/base64                    |
| encode data using Base64 via WinAPI (2 matches)      | data-manipulation/encoding/base64                    |
| encode data using XOR (15 matches)                   | data-manipulation/encoding/xor                       |
| encrypt or decrypt via WinCrypt                      | data-manipulation/encryption                         |
| encrypt data using AES via WinAPI                    | data-manipulation/encryption/aes                     |
| generate random numbers via WinAPI                   | data-manipulation/prng                               |
| contain a resource (.rsrc) section                   | executable/pe/section/rsrc                           |
| extract resource via kernel32 functions              | executable/resource                                  |
| contain an embedded PE file                          | executable/subfile/pe                                |
| accept command line arguments (2 matches)            | host-interaction/cli                                 |
| interact with driver via control codes (4 matches)   | host-interaction/driver                              |
| query environment variable                           | host-interaction/environment-variable                |
| get common file path (6 matches)                     | host-interaction/file-system                         |
| read raw disk data                                   | host-interaction/file-system                         |
| delete file (3 matches)                              | host-interaction/file-system/delete                  |
| check if file exists (6 matches)                     | host-interaction/file-system/exists                  |
| enumerate files recursively                          | host-interaction/file-system/files/list              |
| get file size (3 matches)                            | host-interaction/file-system/meta                    |
| read file (3 matches)                                | host-interaction/file-system/read                    |
| write file (7 matches)                               | host-interaction/file-system/write                   |
| get disk information                                 | host-interaction/hardware/storage                    |
| enumerate network shares                             | host-interaction/network                             |
| get local IPv4 addresses                             | host-interaction/network/address                     |
| resolve DNS                                          | host-interaction/network/dns/resolve                 |
| get networking interfaces                            | host-interaction/network/interface                   |
| shutdown system                                      | host-interaction/os                                  |
| get hostname (2 matches)                             | host-interaction/os/hostname                         |
| check OS version (2 matches)                         | host-interaction/os/version                          |
| create process (4 matches)                           | host-interaction/process/create                      |
| enumerate processes (2 matches)                      | host-interaction/process/list                        |
| acquire debug privileges                             | host-interaction/process/modify                      |
| modify access privileges                             | host-interaction/process/modify                      |
| terminate process (3 matches)                        | host-interaction/process/terminate                   |
| create thread (11 matches)                           | host-interaction/thread/create                       |
| resume thread (3 matches)                            | host-interaction/thread/resume                       |
| terminate thread                                     | host-interaction/thread/terminate                    |
| link function at runtime (4 matches)                 | linking/runtime-linking                              |
| linked against ZLIB                                  | linking/static/zlib                                  |
| parse PE exports (2 matches)                         | load-code/pe                                         |
| parse PE header (3 matches)                          | load-code/pe                                         |
+------------------------------------------------------+------------------------------------------------------+

```

**Comment by williballenthin** [comment]
thanks @davidep for reporting this issue!

looks like the sample has a single export that it exports solely by ordinal and not by name:

![image](https://user-images.githubusercontent.com/156560/127015384-fc1a267d-027a-4b73-bf9b-ecdc5d0fa82f.png)

however, our lightweight pefile extractor doesn't validate that a name exists:

https://github.com/fireeye/capa/blob/e29922af57abb8b799d151b48d42f6c09c9de3fd/capa/features/extractors/pefile.py#L35-L37

i'll fix this bug today and it will be included in the next point release.

**Comment by williballenthin** [comment]
this is a #good-first-issue for anyone that would like to start contributing to capa

**Comment by davidep** [comment]
> thanks @davidep for reporting this issue!
> 

Thank you @williballenthin for the quick root cause finding and the great work ;)
