### ISSUE TITLE
KeyError: 0

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#703]
```
   1   │ WARNING:capa:--------------------------------------------------------------------------------
   2   │ WARNING:capa: This sample appears to be packed.
   3   │ WARNING:capa:
   4   │ WARNING:capa: Packed samples have often been obfuscated to hide their logic.
   5   │ WARNING:capa: capa cannot handle obfuscation well. This means the results may be misleading or incomplete.
   6   │ WARNING:capa: If possible, you should try to unpack this input file before analyzing it with capa.
   7   │ WARNING:capa:
   8   │ WARNING:capa: Identified via rule: (internal) packer file limitation
   9   │ WARNING:capa:
  10   │ WARNING:capa: Use -v or -vv if you really want to see the capabilities identified by capa.
  11   │ WARNING:capa:--------------------------------------------------------------------------------
  12   │ WARNING:capa:--------------------------------------------------------------------------------
  13   │ WARNING:capa: This sample appears to be packed.
  14   │ WARNING:capa:
  15   │ WARNING:capa: Packed samples have often been obfuscated to hide their logic.
  16   │ WARNING:capa: capa cannot handle obfuscation well. This means the results may be misleading or incomplete.
  17   │ WARNING:capa: If possible, you should try to unpack this input file before analyzing it with capa.
  18   │ WARNING:capa:
  19   │ WARNING:capa: Identified via rule: (internal) packer file limitation
  20   │ WARNING:capa:
  21   │ WARNING:capa: Use -v or -vv if you really want to see the capabilities identified by capa.
  22   │ WARNING:capa:--------------------------------------------------------------------------------
  23   │ Traceback (most recent call last):
  24   │   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  25   │     return _run_code(code, main_globals, None,
  26   │   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  27   │     exec(code, run_globals)
  28   │   File "/home/user/code/capa-pub/capa/main.py", line 991, in <module>
  29   │     sys.exit(main())
  30   │   File "/home/user/code/capa-pub/capa/main.py", line 925, in main
  31   │     print(capa.render.json.render(meta, rules, capabilities))
  32   │   File "/home/user/code/capa-pub/capa/render/json.py", line 30, in render
  33   │     capa.render.result_document.convert_capabilities_to_result_document(meta, rules, capabilities),
  34   │   File "/home/user/code/capa-pub/capa/render/result_document.py", line 314, in convert_capabilities_to_result_document
  35   │     "matches": {
  36   │   File "/home/user/code/capa-pub/capa/render/result_document.py", line 315, in <dictcomp>
  37   │     addr: convert_match_to_result_document(rules, capabilities, match) for (addr, match) in matches
  38   │   File "/home/user/code/capa-pub/capa/render/result_document.py", line 117, in convert_match_to_result_document
  39   │     "children": [convert_match_to_result_document(rules, capabilities, child) for child in result.children],
  40   │   File "/home/user/code/capa-pub/capa/render/result_document.py", line 117, in <listcomp>
  41   │     "children": [convert_match_to_result_document(rules, capabilities, child) for child in result.children],
  42   │   File "/home/user/code/capa-pub/capa/render/result_document.py", line 202, in convert_match_to_result_document
  43   │     convert_match_to_result_document(rules, capabilities, rule_matches[location])
  44   │ KeyError: 0
```

**Comment by williballenthin** [comment]
seems to have to do with namespace matches and a disconnect in locations.

**Comment by williballenthin** [comment]
if we have a file scope rule that contains a namespace match statement, and then a rule in this namespace matches at the function level, the file scope rule lists its location as 0x0 while the function scope rule lists its location at e.g. 0x40100. 

we'd want the function scope rule's locations to be reported under the namespace matches.

need to figure out if the bug is introduced during matching or reporting. during reporting we may not have all the context around scopes.
