### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#712]
```
   1   │ Traceback (most recent call last):
   2   │   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
   3   │     return _run_code(code, main_globals, None,
   4   │   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
   5   │     exec(code, run_globals)
   6   │   File "/home/user/code/capa-pub/capa/main.py", line 991, in <module>
   7   │     sys.exit(main())
   8   │   File "/home/user/code/capa-pub/capa/main.py", line 899, in main
   9   │     extractor = get_extractor(
  10   │   File "/home/user/code/capa-pub/capa/main.py", line 464, in get_extractor
  11   │     vw = get_workspace(path, format, sigpaths)
  12   │   File "/home/user/code/capa-pub/capa/main.py", line 412, in get_workspace
  13   │     vw = viv_utils.getWorkspace(path, analyze=False, should_save=False)
  14   │   File "/home/user/env/lib/python3.8/site-packages/viv_utils-0.6.5-py3.8.egg/viv_utils/__init__.py", line 101, in getWorkspace
  15   │     vw.loadFromFile(fp)
  16   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/__init__.py", line 2676, in loadFromFile
  17   │     fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  18   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/parsers/pe.py", line 36, in parseFile
  19   │     return loadPeIntoWorkspace(vw, pe, filename, baseaddr=baseaddr)
  20   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/parsers/pe.py", line 366, in loadPeIntoWorkspace
  21   │     for rva, lname, iname in pe.getImports():
  22   │   File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 452, in getImports
  23   │     return self.imports
  24   │   File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 1172, in __getattr__
  25   │     self.parseImports()
  26   │   File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 796, in parseImports
  27   │     self.imports = self.parseImportTable(x, irva, is_imports=True)
  28   │   File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 851, in parseImportTable
  29   │     ibn_rva = self.readPointerAtRva(imp_by_name+arrayoff)
  30   │   File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 737, in readPointerAtRva
  31   │     return self.readPointerAtOffset(off)
  32   │   File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 733, in readPointerAtOffset
  33   │     return struct.unpack(fmt, self.readAtOffset(off, self.psize))[0]
  34   │ TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by williballenthin** [comment]
need either:
  - viv to handle this case robustly, or
  - a more specific bug from viv that we and handle and format

**Comment by williballenthin** [comment]
this file may be truncated

**Comment by williballenthin** [comment]
https://github.com/vivisect/vivisect/issues/438 and https://github.com/vivisect/vivisect/pull/439
