### ISSUE TITLE
Exception: Invalid String Size: -1

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#714]
```
   1   │ Traceback (most recent call last):
   2   │   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
   3   │     return _run_code(code, main_globals, None,
   4   │   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
   5   │     exec(code, run_globals)
   6   │   File "/home/user/code/capa-pub/capa/main.py", line 991, in <module>
   7   │     sys.exit(main())
   8   │   File "/home/user/code/capa-pub/capa/main.py", line 899, in main
   9   │     extractor = get_extractor(
  10   │   File "/home/user/code/capa-pub/capa/main.py", line 464, in get_extractor
  11   │     vw = get_workspace(path, format, sigpaths)
  12   │   File "/home/user/code/capa-pub/capa/main.py", line 412, in get_workspace
  13   │     vw = viv_utils.getWorkspace(path, analyze=False, should_save=False)
  14   │   File "/home/user/env/lib/python3.8/site-packages/viv_utils-0.6.5-py3.8.egg/viv_utils/__init__.py", line 101, in getWorkspace
  15   │     vw.loadFromFile(fp)
  16   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/__init__.py", line 2676, in loadFromFile
  17   │     fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  18   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/parsers/pe.py", line 36, in parseFile
  19   │     return loadPeIntoWorkspace(vw, pe, filename, baseaddr=baseaddr)
  20   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/parsers/pe.py", line 423, in loadPeIntoWorkspace
  21   │     vw.makeString(rva+baseaddr)
  22   │   File "/home/user/env/lib/python3.8/site-packages/vivisect/__init__.py", line 2118, in makeString
  23   │     raise Exception("Invalid String Size: %d" % size)
  24   │ Exception: Invalid String Size: -1
```

**Comment by williballenthin** [comment]
string size of -1 doesn't make any sense at all

**Comment by williballenthin** [comment]
https://github.com/vivisect/vivisect/issues/433 and https://github.com/vivisect/vivisect/issues/435

**Comment by williballenthin** [comment]
https://github.com/vivisect/vivisect/pull/434 and https://github.com/vivisect/vivisect/pull/436

**Comment by atlas0fd00m** [comment]
cool.  good find.  is this an alignment thing, or is it a off-by-one end-of-section problem?  
can you give an example we can duplicate?

**Comment by atlas0fd00m** [comment]
ahhh.. based on the other issues linked i can see that it's a section that's not being padded with 0's, and a string that slams into the end of the section before finding it's NULL terminator.

this is the offended code:
```    def asciiStringSize(self, va):
        """
        Return the size (in bytes) of the ascii string
        at the specified location (or -1 if no terminator
        is found in the memory map)
        """
        offset, bytez = self.getByteDef(va)
        foff = bytez.find(b'\x00', offset)
        if foff == -1:
            return foff
        return (foff - offset) + 1
```

although from your comments and PR, it looks like the fix is to extend the map to include NULL's to the alignment boundary.

am i with you so far?

**Comment by williballenthin** [comment]
yup, #436 is the more thorough fix (#434 just cleans up the exceptions a tiny bit and suppresses a fatal error). 

the fix proposed there is to round up to the file/section alignment when reading the section data and creating the virtual region.

**Comment by atlas0fd00m** [comment]
i'll check out.
i just made a suggested change which seems to fix the problem with firefox (and i'm guessing other issues that we weren't yet seeing).  hopefully that can help get unittests passing quickly.

i'm out of town starting tomorrow, so i'm trying to help get this fast-tracked.

**Comment by williballenthin** [comment]
fixed upstream, awaiting next viv release
