### ISSUE TITLE
another  UnicodeDecodeError: 'utf-8' codec can't decode byte XXX in position YYY: ZZZ #707 

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#730]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/code/capa-pub/capa/main.py", line 991, in <module>
    sys.exit(main())
  File "/home/user/code/capa-pub/capa/main.py", line 899, in main
    extractor = get_extractor(
  File "/home/user/code/capa-pub/capa/main.py", line 464, in get_extractor
    vw = get_workspace(path, format, sigpaths)
  File "/home/user/code/capa-pub/capa/main.py", line 412, in get_workspace
    vw = viv_utils.getWorkspace(path, analyze=False, should_save=False)
  File "/home/user/env/lib/python3.8/site-packages/viv_utils-0.6.5-py3.8.egg/viv_utils/__init__.py", line 101, in getWorkspace
    vw.loadFromFile(fp)
  File "/home/user/env/lib/python3.8/site-packages/vivisect/__init__.py", line 2676, in loadFromFile
    fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  File "/home/user/env/lib/python3.8/site-packages/vivisect/parsers/pe.py", line 36, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename, baseaddr=baseaddr)
  File "/home/user/env/lib/python3.8/site-packages/vivisect/parsers/pe.py", line 121, in loadPeIntoWorkspace
    dllname = pe.getDllName()
  File "/home/user/env/lib/python3.8/site-packages/PE/__init__.py", line 444, in getDllName
    return rawname.split(b'\x00')[0].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

**Comment by williballenthin** [comment]
dup of #708
