### ISSUE TITLE
elftools.common.exceptions.ELFParseError: expected 4, found 0

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#777]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/code/capa-pub/capa/main.py", line 1112, in <module>
    sys.exit(main())
  File "/home/user/code/capa-pub/capa/main.py", line 973, in main
    pure_file_capabilities, _ = find_file_capabilities(rules, file_extractor, {})
  File "/home/user/code/capa-pub/capa/main.py", line 120, in find_file_capabilities
    for feature, va in itertools.chain(extractor.extract_file_features(), extractor.extract_global_features()):
  File "/home/user/code/capa-pub/capa/features/extractors/elffile.py", line 134, in extract_file_features
    for feature, va in extract_file_features(self.elf, buf):
  File "/home/user/code/capa-pub/capa/features/extractors/elffile.py", line 84, in extract_file_features
    for feature, va in file_handler(elf=elf, buf=buf):  # type: ignore
  File "/home/user/code/capa-pub/capa/features/extractors/elffile.py", line 26, in extract_file_import_names
    symbol_tables = [(idx, s) for idx, s in enumerate(elf.iter_sections()) if isinstance(s, SymbolTableSection)]
  File "/home/user/code/capa-pub/capa/features/extractors/elffile.py", line 26, in <listcomp>
    symbol_tables = [(idx, s) for idx, s in enumerate(elf.iter_sections()) if isinstance(s, SymbolTableSection)]
  File "/home/user/env/lib/python3.8/site-packages/pyelftools-0.27-py3.8.egg/elftools/elf/elffile.py", line 133, in iter_sections
    yield self.get_section(i)
  File "/home/user/env/lib/python3.8/site-packages/pyelftools-0.27-py3.8.egg/elftools/elf/elffile.py", line 113, in get_section
    return self._make_section(section_header)
  File "/home/user/env/lib/python3.8/site-packages/pyelftools-0.27-py3.8.egg/elftools/elf/elffile.py", line 575, in _make_section
    return Section(section_header, name, self)
  File "/home/user/env/lib/python3.8/site-packages/pyelftools-0.27-py3.8.egg/elftools/elf/sections.py", line 37, in __init__
    header = struct_parse(self.structs.Elf_Chdr,
  File "/home/user/env/lib/python3.8/site-packages/pyelftools-0.27-py3.8.egg/elftools/common/utils.py", line 42, in struct_parse
    raise ELFParseError(str(e))
elftools.common.exceptions.ELFParseError: expected 4, found 0
```

**Comment by williballenthin** [comment]
note this happens in lightweight feature extraction not extractor ctor
